export const testimonials = [
    { id: 1, nome: "João Silva", depoimento: "Excelente experiência!", evento: "Festa de Aniversário" },
    { id: 2, nome: "Maria Oliveira", depoimento: "Maravilhoso evento!", evento: "Casamento" },
    { id: 3, nome: "Carlos Souza", depoimento: "Muito bem organizado!", evento: "Conferência" },
    { id: 4, nome: "Ana Pereira", depoimento: "Ótimo serviço!", evento: "Workshop" },
    { id: 5, nome: "Fernando Lima", depoimento: "Tudo perfeito!", evento: "Seminário" },
];

export const drinks = [
    { id: 1, titulo: "Mojito", imagem: "src/images/drinks/amoras.jpeg" },
    { id: 2, titulo: "Caipirinha", imagem: "src/images/drinks/amoras.jpeg" },
    { id: 3, titulo: "Piña Colada", imagem: "src/images/drinks/amoras.jpeg" },
    { id: 4, titulo: "Daiquiri", imagem: "src/images/drinks/amoras.jpeg" },
    { id: 5, titulo: "Margarita", imagem: "src/images/drinks/amoras.jpeg" },
    { id: 6, titulo: "Gin Tônica", imagem: "src/images/drinks/amoras.jpeg" },
];

export const carouselHorizontal = [
    { id: 1, title: "Carrossel 1", image: "src/images/eventos/horizontal/eventos-horizontal(1).jpg" },
    { id: 2, title: "Carrossel 2", image: "src/images/eventos/horizontal/eventos-horizontal(2).jpg" },
    { id: 3, title: "Carrossel 3", image: "src/images/eventos/horizontal/eventos-horizontal(3).jpg" },
    { id: 4, title: "Carrossel 4", image: "src/images/eventos/horizontal/eventos-horizontal(4).jpg" },
    { id: 5, title: "Carrossel 5", image: "src/images/eventos/horizontal/eventos-horizontal(5).jpg" },
    { id: 6, title: "Carrossel 6", image: "src/images/eventos/horizontal/eventos-horizontal(6).jpg" },
    { id: 7, title: "Carrossel 7", image: "src/images/eventos/horizontal/eventos-horizontal(7).jpg" },
    { id: 8, title: "Carrossel 8", image: "src/images/eventos/horizontal/eventos-horizontal(8).jpg" },
    { id: 9, title: "Carrossel 9", image: "src/images/eventos/horizontal/eventos-horizontal(9).jpg" },
    { id: 10, title: "Carrossel 10", image: "src/images/eventos/horizontal/eventos-horizontal(10).jpg" },
    { id: 11, title: "Carrossel 11", image: "src/images/eventos/horizontal/eventos-horizontal(11).jpg" },
    { id: 12, title: "Carrossel 12", image: "src/images/eventos/horizontal/eventos-horizontal(12).jpg" },
    { id: 13, title: "Carrossel 13", image: "src/images/eventos/horizontal/eventos-horizontal(13).jpg" },
    { id: 14, title: "Carrossel 14", image: "src/images/eventos/horizontal/eventos-horizontal(14).jpg" },
    { id: 15, title: "Carrossel 15", image: "src/images/eventos/horizontal/eventos-horizontal(15).jpg" },
    { id: 16, title: "Carrossel 16", image: "src/images/eventos/horizontal/eventos-horizontal(16).jpg" },
    { id: 17, title: "Carrossel 17", image: "src/images/eventos/horizontal/eventos-horizontal(17).jpg" },
    { id: 18, title: "Carrossel 18", image: "src/images/eventos/horizontal/eventos-horizontal(18).jpg" },
    { id: 19, title: "Carrossel 19", image: "src/images/eventos/horizontal/eventos-horizontal(19).jpg" },
    { id: 20, title: "Carrossel 20", image: "src/images/eventos/horizontal/eventos-horizontal(20).jpg" },
    { id: 21, title: "Carrossel 21", image: "src/images/eventos/horizontal/eventos-horizontal(21).jpg" },
    { id: 22, title: "Carrossel 22", image: "src/images/eventos/horizontal/eventos-horizontal(22).jpg" },
    { id: 23, title: "Carrossel 23", image: "src/images/eventos/horizontal/eventos-horizontal(23).jpg" },
    { id: 24, title: "Carrossel 24", image: "src/images/eventos/horizontal/eventos-horizontal(24).jpg" },
    { id: 25, title: "Carrossel 25", image: "src/images/eventos/horizontal/eventos-horizontal(25).jpg" },
    { id: 26, title: "Carrossel 26", image: "src/images/eventos/horizontal/eventos-horizontal(26).jpg" },
    { id: 27, title: "Carrossel 27", image: "src/images/eventos/horizontal/eventos-horizontal(27).jpg" },
    { id: 28, title: "Carrossel 28", image: "src/images/eventos/horizontal/eventos-horizontal(28).jpg" },
    { id: 29, title: "Carrossel 29", image: "src/images/eventos/horizontal/eventos-horizontal(29).jpg" },
    { id: 30, title: "Carrossel 30", image: "src/images/eventos/horizontal/eventos-horizontal(30).jpg" }
];


export const carouselVertical = [
    { id: 1, title: "Carrossel 1", image: "src/images/eventos/vertical/eventos-verticall(1).jpg" },
    { id: 2, title: "Carrossel 2", image: "src/images/eventos/vertical/eventos-verticall(2).jpg" },
    { id: 3, title: "Carrossel 3", image: "src/images/eventos/vertical/eventos-verticall(3).jpg" },
    { id: 4, title: "Carrossel 4", image: "src/images/eventos/vertical/eventos-verticall(4).jpg" },
    { id: 5, title: "Carrossel 5", image: "src/images/eventos/vertical/eventos-verticall(5).jpg" },
    { id: 6, title: "Carrossel 6", image: "src/images/eventos/vertical/eventos-verticall(6).jpg" },
    { id: 7, title: "Carrossel 7", image: "src/images/eventos/vertical/eventos-verticall(7).jpg" },
    { id: 8, title: "Carrossel 8", image: "src/images/eventos/vertical/eventos-verticall(8).jpg" },
    { id: 9, title: "Carrossel 9", image: "src/images/eventos/vertical/eventos-verticall(9).jpg" },
    { id: 10, title: "Carrossel 10", image: "src/images/eventos/vertical/eventos-verticall(10).jpg" },
    { id: 11, title: "Carrossel 11", image: "src/images/eventos/vertical/eventos-verticall(11).jpg" },
    { id: 12, title: "Carrossel 12", image: "src/images/eventos/vertical/eventos-verticall(12).jpg" },
    { id: 13, title: "Carrossel 13", image: "src/images/eventos/vertical/eventos-verticall(13).jpg" },
    { id: 14, title: "Carrossel 14", image: "src/images/eventos/vertical/eventos-verticall(14).jpg" },
    { id: 15, title: "Carrossel 15", image: "src/images/eventos/vertical/eventos-verticall(15).jpg" },
    { id: 16, title: "Carrossel 16", image: "src/images/eventos/vertical/eventos-verticall(16).jpg" },
    { id: 17, title: "Carrossel 17", image: "src/images/eventos/vertical/eventos-verticall(17).jpg" },
    { id: 18, title: "Carrossel 18", image: "src/images/eventos/vertical/eventos-verticall(18).jpg" },
    { id: 19, title: "Carrossel 19", image: "src/images/eventos/vertical/eventos-verticall(19).jpg" },
    { id: 20, title: "Carrossel 20", image: "src/images/eventos/vertical/eventos-verticall(20).jpg" },
    { id: 21, title: "Carrossel 21", image: "src/images/eventos/vertical/eventos-verticall(21).jpg" },
    { id: 22, title: "Carrossel 22", image: "src/images/eventos/vertical/eventos-verticall(22).jpg" },
    { id: 23, title: "Carrossel 23", image: "src/images/eventos/vertical/eventos-verticall(23).jpg" },
    { id: 24, title: "Carrossel 24", image: "src/images/eventos/vertical/eventos-verticall(24).jpg" },
    { id: 25, title: "Carrossel 25", image: "src/images/eventos/vertical/eventos-verticall(25).jpg" },
    { id: 26, title: "Carrossel 26", image: "src/images/eventos/vertical/eventos-verticall(26).jpg" },
    { id: 27, title: "Carrossel 27", image: "src/images/eventos/vertical/eventos-verticall(27).jpg" },
    { id: 28, title: "Carrossel 28", image: "src/images/eventos/vertical/eventos-verticall(28).jpg" },
    { id: 29, title: "Carrossel 29", image: "src/images/eventos/vertical/eventos-verticall(29).jpg" },
    { id: 30, title: "Carrossel 30", image: "src/images/eventos/vertical/eventos-verticall(30).jpg" }
];

